apiVersion: scaffolder.backstage.io/v1beta3

kind: Template

metadata:
  name: aws-ec2-app
  title: Deploy a Web App on AWS EC2
  description: Launches an AWS EC2 instance and deploys a simple web app.
  tags:
    - aws
    - ec2
    - webapp

spec:
  owner: user:manasa
  type: service
  env:
    NODE_OPTIONS: --no-node-snapshot

  parameters:
  - title: AWS Configuration
    required:
      - instance_type
      - region
      - instance_name
    properties:
      instance_name:
        title: Name of the Instance
        type: string
        description: "Can include letters, numbers, and special characters (-, @, $, !, %, *, ?, &)."
        ui:options:
          placeholder: "ec2-name"
          autofocus: true

      instance_type:
        title: EC2 Instance Type
        type: string
        default: t2.micro
        enum:
          - t2.nano
          - t2.micro
          - t2.small
        description: "Select an instance type from the list."

      region:
        title: AWS Region
        type: string
        default: us-east-1
        description: "A region where the instance should be launched."
        ui:options:
          placeholder: "ec2-region"
          autofocus: true

      key_pair:
        title: AWS Key Pair Name
        type: string
        description: "Ensure this key exists in your AWS account."
        ui:options:
          placeholder: "ec2-keypair"
          autofocus: true
    
  - title: Choose a Repository Location
    required:
      - repoUrl
    properties:
      repoUrl:
        title: Location of the repository
        type: string
        ui:field: RepoUrlPicker
        ui:options:
          allowedHosts:
            - github.com


  steps:
    - id: trigger-gh-actions
      name: Trigger GitHub Actions
      action: github:actions:dispatch
      input:
        repoUrl: "github.com?repo=backstage&owner=saimanasak"
        workflowId: "aws-ec2-app.yaml"
        branchOrTagName: "main"  
        workflowInputs:
          instance_type: ${{ parameters.instance_type }}
          aws_region: ${{ parameters.region }}
          instance_name: ${{ parameters.instance_name }}

  output:
    links:
      - title: "EC2 Instance Dashboard"
        url: "https://console.aws.amazon.com/ec2/v2/home"